### ISSUE TITLE
Usage with django-modeltranslation

### ISSUE THREAD

**Issue by malj** [daniyalzade/django_reverse_admin#138]
Hi, first of all great project. 
I'm trying to use it with related models containing fields translated using [`django-modeltranslation`](https://django-modeltranslation.readthedocs.io/en/latest/admin.html#django-admin-integration) which provides admin classes to patch forms for easier translation editing.

```py
from django.contrib.admin import register
from django_reverse_admin import ReverseModelAdmin
from modeltranslation.admin import TranslationInlineModelAdmin
from .models import MyModel

@register(MyModel)
class MyModelAdmin(ReverseModelAdmin):
    inline_type = "stacked"
    inline_reverse = (
        {"field_name": "my_one_to_one_field_name", "admin_class": TranslationInlineModelAdmin},
    )
```
However, I get an error `'DynamicReverseInlineModelAdmin' object has no attribute 'trans_opts'`. The related model fields are properly translated, so I suspect there is a conflict with multiple inheritance with `ReverseInlineModelAdmin`. Manually subclassing both inline model admin classes in reverse order works, but results in duplicate fields:

```py
class TranslationReverseInlineModelAdmin(ReverseInlineModelAdmin, TranslationInlineModelAdmin):
    pass
```
I'd be grateful for any ideas.

**Comment by daniyalzade** [comment]
Hey @malj , i looked into the issue and you can see my work to reproduce this on https://github.com/daniyalzade/django_reverse_admin/tree/bugfix/issue-138. I haven't been able to solve for it yet though. I agree with you that the issue is to do with multiple inheritance, and somehow the TranslationInlineModelAdmin constructor is not being called when you pass it as an admin_class. I will need some more time later to dig deeper into this. Meanwhile, if you make any progress or have suggestions, I am all ears :)

**Comment by malj** [comment]
Hey @daniyalzade, thanks for the follow up.

I checked the code in more detail, and it seems that the issue is in the way `ReverseInlineModelAdmin` is extended. I believe the third argument of `type()` should be a new dict instead an existing superclass' dict, because reusing it overrides the other superclass' constuctor.

I tested it out locally and the test branch you provided seems to work fine:

```py
admin_class_to_use = type(
    str('DynamicReverseInlineModelAdmin'),
    (admin_class, ReverseInlineModelAdmin),
    # dict(admin_class.__dict__, **ReverseInlineModelAdmin.__dict__),
    {}
)
```
