### ISSUE TITLE
AttributeError: 'ForeignKey' object has no attribute 'remote_field'

### ISSUE THREAD

**Issue by asafsarid** [daniyalzade/django_reverse_admin#18]
Hey!
This package looks very useful and I would like to use it. But I am getting this error
`AttributeError: 'ForeignKey' object has no attribute 'remote_field'`
I installed version 1.0.0 as I am using python 2.7.
My Django version is 1.7.4 (is there a similar package for versions < 2.0?)

**Comment by daniyalzade** [comment]
Hey @asafsarid just added support for Django 1.7.4 so that you can start using the package. That said Django 1.7.4 is no longer supported (https://www.djangoproject.com/download/). If you are keen on staying on python2, you should migrate to Django 1.11, but I would suggest moving to python3 and the Django 2.* world. Admin interface is much better there.

In the meantime, you can install `django_reverse_admin==1.1.0` to get the functionality you need. If you spot any bugs and want to contribute you can do it on the python-2 branch.

**Comment by asafsarid** [comment]
Thank you very much @daniyalzade
